CREATE DATABASE LISTA_DE_COMPRAS;
USE LISTA_DE_COMPRAS;
CREATE TABLE COMPRAS(
IDCOMPRAS INT PRIMARY KEY AUTO_INCREMENT,
PRODUTOS_DE_LIMPEZA VARCHAR(50),
VERDURAS VARCHAR(50),
FRUTAS VARCHAR(50),
MANTIMENTOS VARCHAR(50),
BESTEIRAS VARCHAR(50),
BEBIDAS VARCHAR(50)
);
SELECT*FROM COMPRAS;
INSERT INTO COMPRAS
 (PRODUTOS_DE_LIMPEZA,VERDURAS,FRUTAS,MANTIMENTOS,BESTEIRAS,BEBIDAS)VALUE
("DESINFETANTE","BRÓCOLIS","LARANJA","ARROZ","BOLACHA_DE_CHOCOLATE","COCA-COLA"),
("VEJA","CENOURA","MELANCIA","FEIJÃO","SALGADINHO_DE_QUEIJO","TODDYNHO"),
("AMACIANTE","BETERRABA","UVA","MACARRÃO","GOMA","FANTA_UVA"),
("SABÃO_EM_PÓ","ABÓBORA","MORANGO","FARINHA","CHOCOLATE","LEITE");
SELECT*FROM COMPRAS;
UPDATE COMPRAS
SET FRUTAS='MELÃO'
WHERE IDCOMPRAS=1;
SELECT*FROM COMPRAS;
SELECT MANTIMENTOS FROM COMPRAS WHERE IDCOMPRAS=3;
SELECT*FROM COMPRAS WHERE IDCOMPRAS=2;
SELECT*FROM COMPRAS WHERE FRUTAS LIKE'_A%';
SELECT MANTIMENTOS FROM COMPRAS WHERE IDCOMPRAS LIKE '1%';
SELECT MANTIMENTOS FROM COMPRAS WHERE MANTIMENTOS LIKE 'F%';
